#CURSOR
USE HOTEL;
DELIMITER $$
DROP PROCEDURE IF EXISTS GASTOS_SERVICIO_HOTEL $$
create procedure GASTOS_SERVICIO_HOTEL()
BEGIN
DECLARE TODO TEXT;
DECLARE COMPROBAR BOOLEAN DEFAULT FALSE;
DECLARE SERVICIO VARCHAR(10);
DECLARE SERVICIO_1 VARCHAR(10);
DECLARE AÑO VARCHAR(10);
DECLARE AÑO_1 VARCHAR(80);
DECLARE importe DECIMAL(10,2);
-- VARIABLES PARA CONTADORES Y ACUMULADORES
DECLARE TOTAL_AÑO DECIMAL(10,2);
DECLARE TOTAL_SERVICIO DECIMAL(10,2);
DECLARE TOTAL_VENTA_TOTAL DECIMAL(10,2);
-- declaramos cursor
DECLARE GASTOS_SERVICIO CURSOR FOR
	SELECT servicios.NombreSERVICIO, YEAR(servicios.Fecha), (servicios.Precio*gastos.Cantidad) from servicios
	JOIN GASTOS ON gastos.idSERVICIOS = servicios.idSERVICIOS;
-- declaramos continuehandler
DECLARE CONTINUE HANDLER FOR NOT FOUND SET COMPROBAR = TRUE;
OPEN GASTOS_SERVICIO; -- abrimos cursor
SET TODO = 'GASTO POR SERVICIO/AÑO';
SET TOTAL_VENTA_TOTAL = 0; -- INICIAMOS EL TOTAL

-- ABRIMOS EL PRIMER REGISTRO
FETCH GASTOS_SERVICIO INTO SERVICIO, AÑO, IMPORTE;
-- EMPEZAMOS BUCLE
WHILE NOT COMPROBAR DO
	SET SERVICIO_1 = SERVICIO;
    SET TOTAL_AÑO = 0; -- INICIAMOS EL TOTAL GASTADO POR AÑO
    SET TODO = CONCAT(TODO,CHAR(13),'TIPO SERVICIO: ' ,SERVICIO_1); -- IMPRIMIMOS
		-- EMPEZAMOS BUCLE   
		WHILE SERVICIO_1 = SERVICIO AND NOT COMPROBAR DO
			SET AÑO_1 = AÑO;
            SET TOTAL_SERVICIO =0;
			SET TODO = CONCAT(TODO,CHAR(13),'AÑO: ' ,AÑO_1); -- IMPRIMIMOS
            SET TODO= CONCAT(TODO,CHAR(20),'FECHA',SPACE(5),'IMPORTE');
				-- EMPEZAMOS BUCLE   
				WHILE  AÑO_1 = AÑO AND SERVICIO_1 = SERVICIO AND NOT COMPROBAR DO
                SET TOTAL_SERVICIO = TOTAL_SERVICIO + IMPORTE;-- ACUMULAMOS IMPORTES
	
				SET TODO= CONCAT(TODO,CHAR(20),AÑO,SPACE(5),FORMAT(IMPORTE,2));
				FETCH GASTOS_SERVICIO INTO SERVICIO, AÑO, IMPORTE;
				END WHILE; -- FIN BUCLE	
            SET TOTAL_AÑO = TOTAL_AÑO + TOTAL_SERVICIO; 
			SET TODO = CONCAT(TODO,CHAR(25),'TOTAL AÑO ', AÑO_1 , ' :', TOTAL_AÑO); -- IMPRIMIMOS				
            SET TODO = CONCAT(TODO,CHAR(25),'TOTAL :  ',SERVICIO_1 , ' ', TOTAL_SERVICIO); -- IMPRIMIMOS
		END while; -- FIN BUCLE
     
		SET TOTAL_VENTA_TOTAL = TOTAL_VENTA_TOTAL + TOTAL_AÑO; 
		
     
END WHILE; -- FIN BUCLE

SET TODO = CONCAT(TODO,CHAR(25),'TOTAL FINAL :  ', TOTAL_VENTA_TOTAL); -- IMPRIMIMOS

CLOSE GASTOS_SERVICIO;
SELECT TODO INTO OUTFILE '\\resultadogASTOS021.txt'; # va a c:\
END $$

DELIMITER ;

-- EJECUTANDO LA FUNCION
CALL GASTOS_SERVICIO_HOTEL();