USE hotel;

DELIMITER $$

DROP TRIGGER IF EXISTS trig_exam $$
CREATE TRIGGER trig_exam BEFORE INSERT
ON reserva_habitac FOR EACH ROW

BEGIN
DECLARE msg CHAR(255); 
DECLARE err INT; 

IF datediff(NEW.FechaENTRADA, NEW.FechaSALIDA)>30 
OR NEW.FechaENTRADA<now()
THEN
-- CREAR ERROR PARA CANCELAR LA INSERCIÓN
SET msg = CONCAT('reserva no válida ',NEW.FechaENTRADA);
SIGNAL SQLSTATE '02000' SET MESSAGE_TEXT = msg;
SET err=7/0;
END IF; 
	     
END $$

-- COMPROBACIÓN
INSERT INTO reserva_habitac VALUES (DEFAULT,'2016-03-15','2016-03-20',0.07,107,'12345');