#21-OBTENER TODAS LAS PAREJAS DE MARCAS DE NOMBRE QUE SEAN DE LA MISMA CIUDAD
USE TABLASCOCHES;
SELECT DISTINCT A.nombre, B.nombre FROM Marcas A, Marcas B
WHERE A.ciudad =B.ciudad AND A.nombre < B.nombre;