#30-OBTENER EL CIFM Y EL NOMBRE DE LAS MARCAS DE COCHES CUYA SEGUNDA LETRA DEL NOMBRE DE LA
# CIUDAD DE ORIGEN SEA UNA I
USE TABLASCOCHES; 
SELECT Marcas.cifm, Marcas.nombre
FROM Marcas WHERE Marcas.ciudad LIKE '_I%' ;