#42-OBTENER EL NOMBRE Y EL APELLIDO DE LOS CLIENTES CUYO NOMBRE EMPIEZA POR A Y CUYO DNI ES MAYOR
# QUE EL ALGUNO DE LOS CLIENTES QUE SEAN DE MADRID
USE TABLASCOCHES; 
SELECT DISTINCT A.nombre, A.apellidos FROM clientes A, clientes B
WHERE A.nombre LIKE 'A%' AND A.dni > (SELECT B.dni FROM clientes WHERE
B.ciudad LIKE 'MADRID' GROUP BY B.dni );