#46- OBTENER LA MEDIA DE LOS AUTOMOVILES QUE CADA CONCESIONARIO TIENE ACTUALMENTE EN STOCK
USE TABLASCOCHES; 
SELECT AVG(d.cantidad) AS MEDIA_AUT_CONC, c.nombre AS CONCESIONARIO 
FROM distribucion d, concesionarios c
WHERE d.cifc = c.cifc
GROUP BY c.nombre;
