#52-OBTENER LOS NOMBRES DE LOS CLIENTES QUE SOLO HAN COMPRADO EN EL CONCESIONARIO CIFC 0001 DUDA
USE TABLASCOCHES;
SELECT c.nombre, c.dni FROM clientes c where c.dni not IN
(SELECT v.dni FROM ventas v where v.cifc !=1);
