#55-OBTENER EL DNI DE LOS CLIENTES QUE HAN ADQUIRIDO POR LO MENOS LOS
#MISMOS AUTOMOVILES QUE EL CLIENTE LUIS GARCIA
USE TABLASCOCHES;
SELECT clientes.dni FROM clientes WHERE clientes.nombre NOT LIKE 'LUIS GARCIA' AND EXISTS
(SELECT vA.dni FROM ventas vA, ventas vB WHERE vA.codcoche = vB.codcoche
AND EXISTS
(SELECT clientes.dni FROM clientes WHERE clientes.nombre LIKE 'LUIS GARCIA'));