#CREAR UNA VISTA CON LOS JUGADORES QUE PESAN MÁS DE LA MEDIA DE SU EQUIPO O QUE TENGAN MENOS altura DE LA MEDIA DE SU EQUIPO
USE nba;
CREATE OR REPLACE VIEW VISTA_BA AS 
#primero creamos la vista
SELECT e.Division, e.Nombre , AVG(REPLACE(j.Altura,'-','.')) AS MEDIA_ALTURA, AVG(j.Peso) AS MEDIA_PESO 
FROM equipos AS e
JOIN jugadores AS j ON e.Nombre =j.Nombre_equipo
GROUP BY e.Division, e.Nombre;
 #CREAMOS TABLA SOBRE LA TABLA
 CREATE TABLE INFORMACION_JUG AS (SELECT * FROM VISTA_BA);
  #HACEMOS CONSULTA
 SELECT * FROM INFORMACION_JUGADORES;
 #INSERTAR jugadores
 INSERT INTO jugadores
 #CONSULTAR VISTA
 SELECT * FROM VISTA_BA;
# CONSULTAR TABLA ANTIGUA (ANTIGUA)
 SELECT * FROM INFORMACION_JUG;
