#3. Realiza un trigger que actúe antes de borrar un registro en la tabla personal, añadiendo 
#los siguientes datos en la tabla AUDITA_MAESTRO (tipo_modificacion ('D'), nombre_tabla, 
#CODIGO_PER, usuario( USER()), fecha (CURDATE()), terminal (CONNECTION_ID())).
USE academia;
DELIMITER $$
DROP TRIGGER IF EXISTS AUDITORIA_III $$
CREATE TRIGGER AUDITORIA_III BEFORE DELETE
ON alumnos FOR EACH ROW
BEGIN
	DECLARE CLAVE INT;
	INSERT INTO AUDITA_MAESTRO VALUES ("D","ALUMNOS",USER(),CURDATE(),CONNECTION_ID());	
	SET CLAVE=mysql_insert_id();
    
	INSERT INTO AUDITA_DETALLE VALUES (CLAVE,"N_EXP","",OLD.N_EXP);	
	INSERT INTO AUDITA_DETALLE VALUES (CLAVE,"NOMBRE","",OLD.NOMBRE);	
	INSERT INTO AUDITA_DETALLE VALUES (CLAVE,"TELEFONO","",OLD.TELEFONO);	
    INSERT INTO AUDITA_DETALLE VALUES (CLAVE,"CURSO","",OLD.CURSO);
    INSERT INTO AUDITA_DETALLE VALUES (CLAVE,"PERDIDA_PLAZA","",OLD.PERDIDA_PLAZA);
    INSERT INTO AUDITA_DETALLE VALUES (CLAVE,"NOTA_MEDIA","",OLD.NOTA_MEDIA);	
    
    
    
END