/*
5.2 La descripción del producto que más cuesta de una categoría.
*/

DELIMITER $$
DROP FUNCTION IF EXISTS PRODUCTOMCAROCATEGORIA $$
CREATE FUNCTION PRODUCTOMCAROCATEGORIA(CATEGORIA INT) RETURNS VARCHAR(80)
BEGIN
DECLARE TOTAL DECIMAL(10,2);
DECLARE PRODUCTO VARCHAR(80);
SELECT MAX(PR.PRECIOUNIDAD) INTO TOTAL
FROM PRODUCTOS PR 
WHERE PR.idCATEGORIA  = CATEGORIA;

SELECT  PR.nomproducto INTO PRODUCTO 
FROM PRODUCTOS PR 
WHERE PR.PRECIOUNIDAD  = TOTAL
AND PR.idCATEGORIA  = CATEGORIA LIMIT 1;

RETURN PRODUCTO;
end $$
DELIMITER ;
SELECT PRODUCTOMCAROCATEGORIA(46) ;