DELIMITER $$
DROP FUNCTION IF EXISTS PRODUCTOMCAROCATEGORIA $$
CREATE FUNCTION PRODUCTOMCAROCATEGORIA(CATEGORIA INT) RETURNS VARCHAR(80)
BEGIN
DECLARE  PRODUCTO  VARCHAR(80);
SELECT PR.nomproducto INTO PRODUCTO
FROM PRODUCTOS PR where
PR.idCATEGORIA  = CATEGORIA
order by PR.PRECIOUNIDAD desc LIMIT 1;
RETURN PRODUCTO;
end $$
DELIMITER ;
SELECT PRODUCTOMCAROCATEGORIA(46);