/*
5.4 El país que más vendemos en un determinado año.
*/

SELECT  C.IDPAIS , SUM(PRECIOUNIDAD*CANTIDAD) 
FROM PEDIDOSDETA PD JOIN PEDIDOSCABE PC
ON PD.IDPEDIDO = PC.IDPEDIDO
JOIN CLIENTES C ON C.IDCLIENTE = PC.IDCLIENTE
WHERE YEAR(FECHAPEDIDO)=2013
GROUP BY C.IDPAIS
ORDER BY 2 DESC