USE neGOcios2011;
DELIMITER $$
DROP PROCEDURE IF EXISTS detalle1 $$
create procedure detalle1()
BEGIN
DECLARE fin BOOLEAN DEFAULT FALSE;
#DECLARE CONTINUE HANDLER FOR NOT FOUND SET fin = TRUE;
DECLARE idpro int;
DECLARE CANTI int;
DECLARE nombre VARCHAR(20);
declare TOTAL DECIMAL DEFAULT 0;
DECLARE MICURSOR CURSOR FOR
SELECT pR.idPRODUCTO,pR.NOMPRODUCTO, pd.cantidad
FROM  pedidosdeta pd,PRODUCTOS PR
WHERE PD.IDPRODUCTO = pR.idPRODUCTO;

OPEN MI_CURSOR;

FETCH MI_CURSOR INTO idpro, nombre, CANTI;

WHILE NOT NOT FOUND DO

 SELECT idpro, nombre, CANTI;
 SET TOTAL = TOTAL + CANTI;

 
FETCH MI_CURSOR INTO idpro, nombre, CANTI;
  
END WHILE;

SELECT  'CANTIDAD TOTAL: '+ SPACE(2) +STR(TOTAL);


CLOSE MI_CURSOR;


end $$

DELIMITER ;

-- EJECUTANDO LA FUNCION
CALL detalle1();
