#6.- Se desea un informe con nombre de cliente , nombre de producto y una relación de las ventas de
# cada cliente y producto. Totalizar por producto, cliente y final.
USE neGOcios2011;
DELIMITER $$
DROP PROCEDURE IF EXISTS CLIENTE_PRODUCTOS $$
create procedure CLIENTE_PRODUCTOS()
BEGIN
DECLARE TODO TEXT;
DECLARE COMPROBAR BOOLEAN DEFAULT FALSE;
DECLARE CLIENTE VARCHAR(40);
DECLARE CLIENTE_1 VARCHAR(40);
DECLARE PRODUCTO VARCHAR(80);
DECLARE PRODUCTO_1 VARCHAR(80);
DECLARE PRECIO DECIMAL(10,2);
DECLARE CONTADOR_PRODUCTOS INT;
DECLARE CANTIDAD_CLIENTE INT;
DECLARE ACUMULADO_PRODUCTO_CLIENTE DECIMAL(10,2);
DECLARE CANTIDAD_TOTAL INT;
DECLARE TOTAL_VENTA_CLIENTE INT;
DECLARE TOTAL_PRODUCTOS INT;
DECLARE TOTAL_VENTAS DECIMAL(10,2);
-- declaramos cursor
DECLARE CLIENTES_PROD CURSOR FOR
	SELECT clientes.nomcliente , productos.nomproducto, pedidosdetalle.cantidad , 
	pedidosdetalle.preciounidad
	FROM clientes
	JOIN pedidoscabecera ON clientes.idcliente = pedidoscabecera.idcliente  
	JOIN pedidosdetalle ON pedidoscabecera.idpedido	= pedidosdetalle.idpedido
	JOIN productos ON productos.idproducto = pedidosdetalle.idproducto
	ORDER BY 1,2,3,4;
-- declaramos continuehandler
DECLARE CONTINUE HANDLER FOR NOT FOUND SET COMPROBAR = TRUE;
OPEN CLIENTES_PROD; -- abrimos cursor
SET TODO = 'INFORME DE PRODUCTOS CLIENTES';
SET CANTIDAD_CLIENTE = 0; -- INICIAMOS LA CANTIDAD POR CLIENTE
SET TOTAL_VENTA_CLIENTE = 0; -- INICIAMOS EL TOTAL GASTADO POR CLIENTES
SET TOTAL_PRODUCTOS = 0; -- INICIAMOS EL TOTAL DE PRODUCTOS ADQUIRIDOS
SET TOTAL_VENTAS = 0; -- INICIAMOS EL TOTAL DE PRODUCTOS ADQUIRIDOS
-- ABRIMOS EL PRIMER REGISTRO
FETCH CLIENTES_PROD INTO CLIENTE, PRODUCTO, CANTIDAD_CLIENTE, PRECIO;
-- EMPEZAMOS BUCLE
WHILE NOT COMPROBAR DO
	SET CLIENTE_1 = CLIENTE;
	SET ACUMULADO_PRODUCTO_CLIENTE =0; -- PARA EL TOTAL ADQUIRIDO POR CLIENTE
    SET TOTAL_VENTA_CLIENTE = 0; -- PARA EL TOTAL GASTADO POR CLIENTE
    SET TODO = CONCAT(TODO,CHAR(13),'CLIENTE: ' ,CLIENTE); -- IMPRIMIMOS
    set TODO = CONCAT(TODO,CHAR(20),'PRODUCTO              ','  CANTIDAD      ', '  PRECIO PRODUCTO   ', '   TOTAL PRECIO*CANTIDAD'); -- IMPRIMIMOS
		-- EMPEZAMOS BUCLE   
		WHILE CLIENTE_1 = CLIENTE AND NOT COMPROBAR DO
		SET CONTADOR_PRODUCTOS = 0; -- PARA CONTAR PRODUCTOS POR CLIENTE
        SET ACUMULADO_PRODUCTO_CLIENTE = ACUMULADO_PRODUCTO_CLIENTE + CANTIDAD_CLIENTE;
        SET TOTAL_VENTA_CLIENTE = TOTAL_VENTA_CLIENTE + (CANTIDAD_CLIENTE*PRECIO);
		set TODO = CONCAT(TODO,CHAR(25),PRODUCTO,SPACE(5),CANTIDAD_CLIENTE,SPACE(5),FORMAT(PRECIO,2),SPACE(5),
        FORMAT(CANTIDAD_CLIENTE*PRECIO,2),CHAR(25));-- IMPRIMIMOS
		FETCH CLIENTES_PROD INTO CLIENTE, PRODUCTO, CANTIDAD_CLIENTE, PRECIO;
        
			-- EMPEZAMOS BUCLE   
			WHILE PRODUCTO_1 = PRODUCTO AND NOT COMPROBAR DO
			SET CONTADOR_PRODUCTOS = CONTADOR_PRODUCTOS + CANTIDAD_CLIENTE;
			FETCH CLIENTES_PROD INTO CLIENTE, PRODUCTO, CANTIDAD_CLIENTE, PRECIO;
			END while; -- FIN BUCLE	
            
        SET TODO = CONCAT(TODO,CHAR(25),'CLIENTE: ' ,CLIENTE_1, ' HA COMPRADO ', CONTADOR_PRODUCTOS,SPACE(8), ' DE ', PRODUCTO_1); -- IMPRIMIMOS		     
        
		END while; -- FIN BUCLE
        
	-- ACUMULAMOS
    SET TOTAL_PRODUCTOS = TOTAL_PRODUCTOS + ACUMULADO_PRODUCTO_CLIENTE;
	SET TOTAL_VENTAS = TOTAL_VENTAS + TOTAL_VENTA_CLIENTE;    
	SET TODO = CONCAT(TODO,CHAR(25),'CLIENTE: ' ,CLIENTE_1, ' HA COMPRADO ', ACUMULADO_PRODUCTO_CLIENTE, ' PRODUCTOS'); -- IMPRIMIMOS		
	SET TODO = CONCAT(TODO,CHAR(25),'CLIENTE: ' ,CLIENTE_1, ' SE HA GASTADO ', TOTAL_VENTA_CLIENTE, ' EUROS'); -- IMPRIMIMOS			
END WHILE; -- FIN BUCLE

SET TODO = CONCAT(TODO,CHAR(25),'LOS CLIENTES HAN COMPRADO ', TOTAL_PRODUCTOS,SPACE(8), ' PRODUCTOS EN TOTAL'); -- IMPRIMIMOS		
SET TODO = CONCAT(TODO,CHAR(25),'LOS CLIENTES SE HAN GASTADO ', TOTAL_VENTAS,SPACE(16), ' EUROS EN TOTAL'); -- IMPRIMIMOS

CLOSE CLIENTES_PROD;
SELECT TODO INTO OUTFILE '\\result999.txt'; # va a c:\
END $$

DELIMITER ;

-- EJECUTANDO LA FUNCION
CALL CLIENTE_PRODUCTOS();
