#5.-  Mostrar  los productos por cada proveedor mostrando el precio de cada
#artículo y el precio medio por proveedor y final.
USE neGOcios2011;
DELIMITER $$
DROP PROCEDURE IF EXISTS PRODUCTOS_PROVEEDOR_MEDIO $$
CREATE PROCEDURE PRODUCTOS_PROVEEDOR_MEDIO()
BEGIN
-- variables
DECLARE TODO TEXT;
DECLARE COMPROBAR BOOLEAN DEFAULT FALSE;
DECLARE PROVEEDOR VARCHAR(20);
DECLARE PROVEEDOR_1 VARCHAR(20);
DECLARE PRODUCTO VARCHAR(20);
DECLARE PRODUCTO_1 VARCHAR(20);
DECLARE CONTADOR_articulos_proveedor INT;
DECLARE CONTADOR_PROVEEDORES INT;
DECLARE PRECIO INT;
DECLARE PRECIO_PROVEEDOR_MEDIO DECIMAL;
DECLARE PRECIO_PROVEEDORES_TOTALES DECIMAL;
-- declaramos cursor
DECLARE PRODUCTOS_PROVEEDOR CURSOR FOR
	SELECT proveedores.nomproveedor, productos.nomproducto, productos.preciounidad
    FROM proveedores
    JOIN productos ON productos.idproveedor = proveedores.idproveedor
    ORDER BY 1,2,3;
-- declaramos continuehandler
DECLARE CONTINUE HANDLER FOR NOT FOUND SET COMPROBAR = TRUE;
OPEN PRODUCTOS_PROVEEDOR; -- abrimos cursor
SET TODO = 'INFORME DE PRODUCTOS PROVEEDORES';
SET PRECIO_PROVEEDORES_TOTALES = 0;
SET CONTADOR_PROVEEDORES = 0;
FETCH PRODUCTOS_PROVEEDOR INTO PROVEEDOR, PRODUCTO, PRECIO;
-- EMPEZAMOS BUCLE
WHILE NOT COMPROBAR DO
	SET PROVEEDOR_1 = PROVEEDOR;
    SET PRECIO_PROVEEDOR_MEDIO = 0;
	SET CONTADOR_articulos_proveedor =0;
    SET TODO = CONCAT(TODO,CHAR(13),'PROVEEDOR: ' ,PROVEEDOR); -- IMPRIMIMOS
    set TODO = CONCAT(TODO,CHAR(13),'ARTICULO      ','PRECIO'); -- IMPRIMIMOS
		-- EMPEZAMOS BUCLE   
		WHILE PROVEEDOR_1 = PROVEEDOR AND NOT COMPROBAR DO
		SET CONTADOR_articulos_proveedor = CONTADOR_articulos_proveedor + 1; -- INICIAMOS CONTADOR ARTICULOS PROVEEDOR
		SET PRECIO_PROVEEDOR_MEDIO = PRECIO_PROVEEDOR_MEDIO + PRECIO;-- PRECIO MEDIO PROVEEDOR
		set TODO = CONCAT(TODO,CHAR(13),PRODUCTO,SPACE(5),FORMAT(PRECIO,2));-- IMPRIMIMOS
		FETCH PRODUCTOS_PROVEEDOR INTO PROVEEDOR, PRODUCTO, PRECIO;
		END while; -- FIN BUCLE
	SET CONTADOR_PROVEEDORES = CONTADOR_PROVEEDORES + CONTADOR_articulos_proveedor;-- CONTAMOS TODO LOS ARTICULOS
    SET PRECIO_PROVEEDORES_TOTALES = PRECIO_PROVEEDORES_TOTALES + PRECIO_PROVEEDOR_MEDIO;-- CONTAMOS TODO LOS PRECIOS
	SET TODO = CONCAT(TODO,CHAR(13),'PRECIO MEDIO PROVEEDOR: '
    ,FORMAT(PRECIO_PROVEEDOR_MEDIO/CONTADOR_articulos_proveedor,2),CHAR(13)); -- IMPRIMIMOS
    
END WHILE; -- FIN BUCLE

SET TODO = CONCAT(TODO,CHAR(13),'PRECIO MEDIO TOTAL PROVEEDORES: ',
FORMAT(PRECIO_PROVEEDORES_TOTALES/CONTADOR_PROVEEDORES,2)); -- IMPRIMIMOS

CLOSE PRODUCTOS_PROVEEDOR;
SELECT TODO INTO OUTFILE '\\result77.txt'; # va a c:\
END $$

DELIMITER ;

-- EJECUTANDO LA FUNCION
CALL PRODUCTOS_PROVEEDOR_MEDIO();


