#6.- Se desea un informe con nombre de cliente , nombre de producto y una relación de las ventas de
# cada cliente y producto. Totalizar por producto, cliente y final.
USE neGOcios2011;
DELIMITER $$
DROP PROCEDURE IF EXISTS CLIENTE_PRODUCTOS $$
create procedure CLIENTE_PRODUCTOS()
BEGIN
DECLARE TODO TEXT;
DECLARE COMPROBAR BOOLEAN DEFAULT FALSE;
DECLARE CLIENTE VARCHAR(40);
DECLARE CLIENTE_1 VARCHAR(40);
DECLARE PRODUCTO VARCHAR(80);
DECLARE PRODUCTO_1 VARCHAR(80);
DECLARE ID_PEDIDO INT(11);
DECLARE ID_PEDIDO_1 INT(11);
DECLARE PRECIO DECIMAL(10,2);
-- VARIABLES PARA CONTADORES Y ACUMULADORES
DECLARE CANTIDAD INT;
DECLARE ACUMULADO_PRODUCTO_CLIENTE DECIMAL(10,2);
DECLARE TOTAL_VENTA_CLIENTE DECIMAL(10,2);
DECLARE TOTAL_VENTA_TOTAL DECIMAL(10,2);
-- declaramos cursor
DECLARE CLIENTES_PROD CURSOR FOR
	SELECT clientes.nomcliente , productos.nomproducto, pedidosdetalle.cantidad , pedidosdetalle.idpedido, 
	pedidosdetalle.preciounidad
	FROM clientes
	JOIN pedidoscabecera ON clientes.idcliente = pedidoscabecera.idcliente  
	JOIN pedidosdetalle ON pedidoscabecera.idpedido	= pedidosdetalle.idpedido
	JOIN productos ON productos.idproducto = pedidosdetalle.idproducto
	ORDER BY 1,2;
-- declaramos continuehandler
DECLARE CONTINUE HANDLER FOR NOT FOUND SET COMPROBAR = TRUE;
OPEN CLIENTES_PROD; -- abrimos cursor
SET TODO = 'INFORME DE PRODUCTOS CLIENTES';
SET TOTAL_VENTA_TOTAL = 0; -- INICIAMOS EL TOTAL

-- ABRIMOS EL PRIMER REGISTRO
FETCH CLIENTES_PROD INTO CLIENTE, PRODUCTO, CANTIDAD,ID_PEDIDO, PRECIO;
-- EMPEZAMOS BUCLE
WHILE NOT COMPROBAR DO
	SET CLIENTE_1 = CLIENTE;
    SET TOTAL_VENTA_CLIENTE = 0; -- INICIAMOS EL TOTAL GASTADO POR CLIENTES
    SET TODO = CONCAT(TODO,CHAR(13),'CLIENTE: ' ,CLIENTE); -- IMPRIMIMOS
		-- EMPEZAMOS BUCLE   
		WHILE CLIENTE_1 = CLIENTE AND NOT COMPROBAR DO
			SET PRODUCTO_1 = PRODUCTO;
            SET ACUMULADO_PRODUCTO_CLIENTE =0;
			SET TODO = CONCAT(TODO,CHAR(13),'PRODUCTO: ' ,PRODUCTO_1); -- IMPRIMIMOS
				-- EMPEZAMOS BUCLE   
				WHILE PRODUCTO_1 = PRODUCTO AND CLIENTE_1 = CLIENTE AND NOT COMPROBAR DO
                SET ACUMULADO_PRODUCTO_CLIENTE = ACUMULADO_PRODUCTO_CLIENTE + PRECIO*CANTIDAD;-- ACUMULAMOS PRECIOS
				SET TODO= CONCAT(TODO,CHAR(13),ID_PEDIDO,SPACE(8),FORMAT(PRECIO*CANTIDAD,2));
				FETCH CLIENTES_PROD INTO CLIENTE, PRODUCTO, CANTIDAD,ID_PEDIDO, PRECIO;
				END while; -- FIN BUCLE	
            SET TOTAL_VENTA_CLIENTE = TOTAL_VENTA_CLIENTE + ACUMULADO_PRODUCTO_CLIENTE; 
			SET TODO = CONCAT(TODO,CHAR(25),'TOTAL PRODUCTO :  ', ACUMULADO_PRODUCTO_CLIENTE); -- IMPRIMIMOS				
            
		END while; -- FIN BUCLE
     
		SET TOTAL_VENTA_TOTAL = TOTAL_VENTA_TOTAL + TOTAL_VENTA_CLIENTE; 
		SET TODO = CONCAT(TODO,CHAR(25),'TOTAL CLIENTE :  ', TOTAL_VENTA_CLIENTE); -- IMPRIMIMOS
     
END WHILE; -- FIN BUCLE

SET TODO = CONCAT(TODO,CHAR(25),'TOTAL FINAL :  ', TOTAL_VENTA_TOTAL); -- IMPRIMIMOS

CLOSE CLIENTES_PROD;
SELECT TODO INTO OUTFILE '\\resultadoClientes.txt'; # va a c:\
END $$

DELIMITER ;

-- EJECUTANDO LA FUNCION
CALL CLIENTE_PRODUCTOS();