#3.- Mostrar los pedidos del año 2012 en que se han vendido cada artículo, con totales por artículo y total final.
# Sólo se tendrán en cuenta los pedidos del año 2012.
USE neGOcios2011;
DELIMITER $$
DROP PROCEDURE IF EXISTS PEDIDOS_2012 $$
create procedure PEDIDOS_2012()
begin
# DECLARO VARIABLES DE TRABAJO
DECLARE IDPEDIDO INT;
DECLARE IDPEDIDO_1 INT;
DECLARE TOTAL_ARTICULOS, TOTAL_PEDIDO_ARTICULOS ,TOTAL_final_PEDIDO DECIMAL;
DECLARE todo text;
DECLARE COMPROBAR BOOLEAN DEFAULT FALSE;
DECLARE MI_CURSOR_PEDIDOS_12 CURSOR FOR
	SELECT pedidoscabecera.idpedido , 
	COUNT(productos.idproducto) FROM productos
	JOIN pedidosdetalle ON pedidosdetalle.idproducto = productos.idproducto
	JOIN pedidoscabecera ON pedidoscabecera.idpedido = pedidosdetalle.idpedido
	WHERE YEAR(pedidoscabecera.fechapedido) = 2012
	GROUP BY pedidoscabecera.idpedido
	ORDER BY 1;
#DECLARO EL BUCLE PARA EL BOOLEAN
DECLARE CONTINUE HANDLER FOR NOT FOUND SET COMPROBAR = TRUE;
-- ABRIR EL CURSOR
OPEN MI_CURSOR_PEDIDOS_12;
-- TOTALES FINALES 
SET TOTAL_final_PEDIDO=0;
SET TODO = 'INFORME DE PEDIDOS DE PEDIDOS POR PRODUCTO EN 2012 : ';
# DECLARO EL CURSOR

-- LEER EL PRIMER REGISTRO
FETCH MI_CURSOR_PEDIDOS_12 INTO IDPEDIDO, TOTAL_ARTICULOS;
-- MIENTRA HAYA REGISTROS
WHILE not COMPROBAR do
	-- ASIGNAR A LA VARIABLE IDPEDIDO_1 EL VALOR INICIAL DE IDPEDIDO
	SET IDPEDIDO_1 = IDPEDIDO;
	-- IMPRIMIMOS EL PEDIDO
	set todo = concat(todo, char(13),'PEDIDO: ',IDPEDIDO_1);
	-- AQUI VENDRA EN CADA PEDIDO EL TOTAL DE ARTICULOS INICIADO A CERO
	SET TOTAL_PEDIDO_ARTICULOS=0;
	-- EL BUCLE CONTINUA HASTA QUE CAMBIE DE PEDIDO O TERMINEN LOS PEDIDOS
		   -- PRINCIPIO BUCLE
		   WHILE IDPEDIDO_1 = IDPEDIDO AND not COMPROBAR do 
			--  ACUMULAR EL TOTAL
			SET TOTAL_PEDIDO_ARTICULOS =TOTAL_PEDIDO_ARTICULOS+ TOTAL_ARTICULOS;
			-- IMPRIMIR EL REGISTRO
			set todo = concat(todo, char(13),IDPEDIDO,SPACE(5), ' ,NUMERO ARTICULOS ',format(TOTAL_ARTICULOS,2));
			-- LEER EL REGISTRO SIGUIENTE CUANO ACABE CON EL PEDIDO
			FETCH MI_CURSOR_PEDIDOS_12 INTO IDPEDIDO, TOTAL_ARTICULOS;
			END while ; 
			-- FIN DEL BUCLE
	-- TOTAL DE AÑO 
	set todo = concat(todo, char(13),'TOTAL PEDIDOS : ', IDPEDIDO_1 , SPACE(2), 'TOTAL ARTICULOS 2012 : '
     , format(TOTAL_final_PEDIDO,2));
	-- Acumulo total final
	SET TOTAL_final_PEDIDO =TOTAL_final_PEDIDO + TOTAL_PEDIDO_ARTICULOS;      
          
          
 END while;   
-- FIN PROGRAMA
-- CERRAR
CLOSE MI_CURSOR_PEDIDOS_12;
select todo;
select TODO into outfile '\\result5.txt'; # va a c:\
end $$
DELIMITER ;
-- EJECUTANDO LA FUNCION
CALL PEDIDOS_2012();

