DELIMITER $$
DROP TRIGGER IF EXISTS tr_cliente4 $$
CREATE TRIGGER tr_cliente4 AFTER DELETE
ON CLIENTES FOR EACH ROW
BEGIN
#VER SI NO EXISTE MAS CLIENTES CON ESE PAIS
if  NOT EXISTS(SELECT * FROM  CLIENTES C
    WHERE C.pais=OLD.PAIS) THEN    
	DELETE FROM paises WHERE PAIS=OLD.PAIS; 
END IF;
END $$
DELIMITER ; 
