#3.- Juntar los dos anteriores en solo trigger.
USE hotel;
DELIMITER $$
DROP TRIGGER IF EXISTS INSERCION_CLIENTES $$

CREATE TRIGGER INSERCION_CLIENTES AFTER INSERT, UPDATE
ON clientes FOR EACH ROW

BEGIN
	IF (NEW.PAIS NOT IN (SELECT PAIS FROM PAISES) ) THEN
		INSERT INTO PAISES (PAIS) VALUES(NEW.PAIS);
	END IF;
END