CREATE TABLE AUDITA_MAESTRO(
ID_MAES INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
TIPO_MODIFICACION VARCHAR( 1 ) ,
NOMBRE_TABLA VARCHAR( 50 ) ,
USUARIO VARCHAR( 50 ) ,
FECHA DATE,
TERMINAL VARCHAR( 50 )
)