DELIMITER $$
DROP PROCEDURE IF EXISTS USP_AGREGAPEDIDO $$
CREATE PROCEDURE USP_AGREGAPEDIDO(
in IDPED INT,
IDCLI VARCHAR(5),
IDEMP INT,
FECPED DATETIME,
IDPROD INT,
PRE DECIMAL,
CANT INT,
out SALIDA varchar(100))
BEGIN
DECLARE EXIT HANDLER FOR SQLSTATE '23000'
	SET SALIDA='ERROR';
INSERT INTO PEDIDOSCABE
(IDPEDIDO, IDCLIENTE, IDEMPLEADO, FECHAPEDIDO,destinatario,dirdestinatario,fechaentrega ,fechaenvio,enviopedido)
VALUES
(IDPED, IDCLI, IDEMP, FECPED,'WEFWE','DIRDES','','','');
INSERT INTO PEDIDOSDETA
(IDPEDIDO, IDPRODUCTO, PRECIOUNIDAD, CANTIDAD, DESCUENTO)
VALUES
(IDPED, IDPROD, PRE, CANT, 0);
UPDATE PRODUCTOS 
SET UNIdadesENEXISTENCIA =UNIdadesENEXISTENCIA-CANT  
WHERE IDPRODUCTO = IDPROD;
END$$
DELIMITER ;
CALL USP_AGREGAPEDIDO(219,'NCBCK', 1,'01-01-2014',
15,10.2,1,@SALIDA);
SELECT @SALIDA;


