#11-OBTENER EL CIFC DE TODOS LOS CONCESIONARIOS CUYA CANTIDAD ENLA TABLA DE DISTRIBUCION ENTRE 10 Y 18 AMBOS INCLUSIVE
USE TABLASCOCHES;
SELECT Concesionarios.cifc FROM Concesionarios
WHERE Concesionarios.cifc IN (SELECT Distribucion.cifc FROM Distribucion
WHERE Distribucion.cantidad BETWEEN 10 AND 18);