DELIMITER $$
DROP TRIGGER IF EXISTS Empleado_U_B $$
CREATE TRIGGER Empleado_U_B BEFORE UPDATE
ON empleado FOR EACH ROW

BEGIN
IF (NEW.SALARIO>3000 AND OLD.SALARIO<=3000 AND OLD.RETENCION <20) THEN
  SET NEW.RETENCION=NEW.RETENCION+5 ;
  
END IF;
END $$