
create database academia;

USE academia;

CREATE TABLE IF NOT EXISTS avisos (
  N_EXP varchar(10) NOT NULL,
  DIA DATE NOT NULL,
  HORA TIME NOT NULL,
  TELEFONO VARCHAR(10),
  PRIMARY KEY (N_EXP)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE IF NOT EXISTS faltas (
  N_EXP varchar(10) NOT NULL,
  DIA DATE NOT NULL,
  HORA TIME NOT NULL,
  JUSTIFICADA VARCHAR(10) NOT NULL,
  PRIMARY KEY (N_EXP)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS alumnos (
  N_EXP varchar(10) NOT NULL,
  NOMBRE varchar(25) NOT NULL,
  TELEFONO varchar(10) NOT NULL,
  CURSO varchar(4) NOT NULL,
  PERDIDA_PLAZA varchar(1) NOT NULL,
  NOTA_MEDIA FLOAT NOT NULL,
  PRIMARY KEY (N_EXP)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS observaciones (
  N_EXP varchar(10) NOT NULL,
  EVALUACION varchar(10) NOT NULL,
  OBSERVACION varchar(100) NOT NULL,
  PRIMARY KEY (N_EXP)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS notas (
  N_EXP varchar(10) NOT NULL,
  EVALUACION varchar(10) NOT NULL,
  NOTA FLOAT NOT NULL,
  PRIMARY KEY (N_EXP)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;