USE academia;

CREATE TABLE AUDITA_MAESTRO(
ID_MAES INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
TIPO_MODIFICACION VARCHAR(1) ,
NOMBRE_TABLA VARCHAR( 50 ) ,
USUARIO VARCHAR( 50 ) ,
FECHA DATE,
TERMINAL VARCHAR( 50 )
);

CREATE TABLE AUDITA_DETALLE(
ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
ID_MAES INTEGER ,
NOMBRE_CAMPO VARCHAR( 50 ) ,
VALOR_NUEVO VARCHAR( 50 ) ,
VALOR_ANTERIOR VARCHAR( 50 )
)